const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //admin
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    SAVE_USER_SUCCESS: 'SAVE_USER_SUCCESS',
    SAVE_USER_FAILED: 'SAVE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILED: 'FETCH_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    FETCH_TOPDOCTOR_SUCCESS: 'FETCH_TOPDOCTOR_SUCCESS',
    FETCH_TOPDOCTOR_FAILED: 'FETCH_TOPDOCTOR_FAILED',

    FETCH_ALLDOCTOR_SUCCESS: 'FETCH_ALLDOCTOR_SUCCESS',
    FETCH_ALLDOCTOR_FAILED: 'FETCH_ALLDOCTOR_FAILED',

    SAVE_INFODOCTOR_SUCCESS: 'SAVE_INFODOCTOR_SUCCESS',
    SAVE_INFODOCTOR_FAILED: 'SAVE_INFODOCTOR_FAILED',

    FETCH_DETAILDOCTOR_SUCCESS: 'FETCH_DETAILDOCTOR_SUCCESS',
    FETCH_DETAILDOCTOR_FAILED: 'FETCH_DETAILDOCTOR_FAILED',

    FETCH_SCHEDULE_SUCCESS: 'FETCH_SCHEDULE_SUCCESS',
    FETCH_SCHEDULE_FAILED: 'FETCH_SCHEDULE_FAILED',

    SAVE_SCHEDULE_SUCCESS: 'SAVE_SCHEDULE_SUCCESS',
    SAVE_SCHEDULE_FAILED: 'SAVE_SCHEDULE_FAILED',

    FETCH_REQUIREDOCTORINFO_SUCCESS: 'FETCH_REQUIREDOCTORINFO_SUCCESS',
    FETCH_REQUIREDOCTORINFO_FAILED: 'FETCH_REQUIREDOCTORINFO_FAILED',

    FETCH_EXTRAINFODOCTOR_SUCCESS: 'FETCH_EXTRAINFODOCTOR_SUCCESS',
    FETCH_EXTRAINFODOCTOR_FAILED: 'FETCH_EXTRAINFODOCTOR_FAILED',

    CONFIRM_BOOKING_SUCCESS: 'CONFIRM_BOOKING_SUCCESS',
    CONFIRM_BOOKING_FAILED: 'CONFIRM_BOOKING_FAILED',

    // FETCH_ALLCLINIC_SUCCESS: 'FETCH_ALLCLINIC_SUCCESS',
    // FETCH_ALLCLINIC_FAILED: 'FETCH_ALLCLINIC_FAILED',


    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
})

export default actionTypes;